/** Katalogeintrag; id verbindet DOM-Auswahl, Physikkörper und API-Bewertung. */
export type Emoji = { id: string; symbol: string; label: string };
/** Kompakte Katalogdaten im Format Symbol|Bezeichnung; die Reihenfolge bestimmt die IDs. */
const entries = [
  '🍏|Grüner Apfel',
  '🍎|Roter Apfel',
  '🍐|Birne',
  '🍊|Mandarine',
  '🍋|Zitrone',
  '🍌|Banane',
  '🍉|Wassermelone',
  '🍇|Weintrauben',
  '🍓|Erdbeere',
  '🫐|Blaubeeren',
  '🍈|Honigmelone',
  '🍒|Kirschen',
  '🍑|Pfirsich',
  '🥭|Mango',
  '🍍|Ananas',
  '🥥|Kokosnuss',
  '🥝|Kiwi',
  '🍅|Tomate',
  '🍆|Aubergine',
  '🥑|Avocado',
  '🥦|Brokkoli',
  '🥬|Blattgemüse',
  '🥒|Gurke',
  '🌶️|Chili',
  '🫑|Paprika',
  '🌽|Mais',
  '🥕|Karotte',
  '🫒|Oliven',
  '🧄|Knoblauch',
  '🧅|Zwiebel',
  '🥔|Kartoffel',
  '🍠|Süßkartoffel',
  '🥐|Croissant',
  '🥯|Bagel',
  '🍞|Brot',
  '🥖|Baguette',
  '🥨|Brezel',
  '🧀|Käse',
  '🥚|Ei',
  '🍳|Spiegelei',
  '🥞|Pfannkuchen',
  '🧇|Waffel',
  '🥓|Speck',
  '🥩|Steak',
  '🍗|Hähnchenkeule',
  '🌭|Hotdog',
  '🍔|Hamburger',
  '🍟|Pommes frites',
  '🍕|Pizza',
  '🥪|Sandwich',
  '🥙|Gefülltes Fladenbrot',
  '🌮|Taco',
  '🌯|Burrito',
  '🥗|Salat',
  '🍝|Spaghetti',
  '🍜|Nudelsuppe',
  '🍣|Sushi',
  '🍩|Donut',
  '🍪|Keks',
  '🎂|Geburtstagstorte',
  '🍰|Kuchen',
  '🧁|Cupcake',
  '🍫|Schokolade',
  '🍬|Bonbon',
  '🍭|Lutscher',
  '🍦|Softeis',
  '🍿|Popcorn',
  '🥜|Erdnüsse',
  '🍯|Honig',
  '🥛|Milch',
  '☕|Kaffee',
  '🍵|Tee',
  '🧃|Saft',
  '🥤|Softdrink',
  '🧋|Bubble Tea',
  '🍺|Bier',
  '🍷|Wein',
  '🍸|Cocktail',
  '💧|Wassertropfen',
  '🐶|Hund',
  '🐱|Katze',
  '🐭|Maus',
  '🐹|Hamster',
  '🐰|Kaninchen',
  '🦊|Fuchs',
  '🐻|Bär',
  '🐼|Panda',
  '🐨|Koala',
  '🐯|Tiger',
  '🦁|Löwe',
  '🐮|Kuh',
  '🐷|Schwein',
  '🐸|Frosch',
  '🐵|Affe',
  '🐔|Huhn',
  '🐧|Pinguin',
  '🐦|Vogel',
  '🦆|Ente',
  '🦉|Eule',
  '🦋|Schmetterling',
  '🐝|Biene',
  '🐞|Marienkäfer',
  '🐢|Schildkröte',
  '🐍|Schlange',
  '🦖|Dinosaurier',
  '🐙|Oktopus',
  '🐠|Tropischer Fisch',
  '🐬|Delfin',
  '🐳|Wal',
  '🦈|Hai',
  '🌸|Kirschblüte',
  '🌻|Sonnenblume',
  '🌹|Rose',
  '🌵|Kaktus',
  '🌲|Nadelbaum',
  '🌴|Palme',
  '🍀|Kleeblatt',
  '🍄|Pilz',
  '☀️|Sonne',
  '🌈|Regenbogen',
  '🎸|Gitarre',
  '🥁|Schlagzeug',
  '🎹|Klavier',
  '🎷|Saxofon',
  '🎺|Trompete',
  '🎻|Geige',
  '🪕|Banjo',
  '🎤|Mikrofon',
  '🎧|Kopfhörer',
  '🎼|Notenblatt',
  '🎵|Musiknote',
  '📻|Radio',
  '🔊|Lautsprecher',
  '🎬|Filmklappe',
  '🎨|Farbpalette',
  '🎭|Theater',
  '📷|Kamera',
  '📚|Bücher',
  '✏️|Bleistift',
  '💻|Laptop',
  '📱|Smartphone',
  '💡|Glühbirne',
  '🔬|Mikroskop',
  '🔭|Teleskop',
  '🧪|Reagenzglas',
  '🛠️|Werkzeug',
  '✂️|Schere',
  '🧵|Garn',
  '🎮|Gamecontroller',
  '🎲|Würfel',
  '⚽|Fußball',
  '🏀|Basketball',
  '🎾|Tennisball',
  '🏈|Football',
  '⚾|Baseball',
  '🏐|Volleyball',
  '🏓|Tischtennis',
  '🏸|Badminton',
  '🥊|Boxhandschuh',
  '🛹|Skateboard',
  '🚲|Fahrrad',
  '🛼|Rollschuhe',
  '⛷️|Skifahrer',
  '🏄|Surfer',
  '🏊|Schwimmer',
  '🚗|Auto',
  '🚌|Bus',
  '🚂|Zug',
  '✈️|Flugzeug',
  '🚀|Rakete',
  '⛵|Segelboot',
  '🏠|Haus',
  '🏕️|Camping',
  '🏖️|Strand',
  '🏔️|Berg',
  '🌍|Erde',
  '🧳|Koffer',
  '🎈|Luftballon',
  '🎁|Geschenk',
  '❤️|Herz',
];
/** Gemeinsamer Katalog für Browser und Server; Umordnen der Einträge verändert ihre IDs. */
export const EMOJIS: Emoji[] = entries.map((entry, index) => {
  const [symbol, label] = entry.split('|');
  return { id: `emoji_${index}`, symbol, label };
});

/** Zweiter Katalog: Smileys, Handzeichen und Menschen mit Gesten. */
export const PEOPLE_EMOJIS: Emoji[] = [
  '😀|Grinsendes Gesicht',
  '😃|Lachendes Gesicht mit großen Augen',
  '😄|Lachendes Gesicht mit lachenden Augen',
  '😁|Strahlendes Gesicht',
  '😆|Lachen mit zugekniffenen Augen',
  '😅|Lachen mit Schweißtropfen',
  '🤣|Sich vor Lachen kugeln',
  '😂|Freudentränen',
  '🙂|Leicht lächelndes Gesicht',
  '🙃|Umgedrehtes Gesicht',
  '🫠|Schmelzendes Gesicht',
  '😉|Zwinkerndes Gesicht',
  '😊|Verlegenes Lächeln',
  '😇|Lächeln mit Heiligenschein',
  '🥰|Verliebt mit Herzen',
  '😍|Herzaugen',
  '🤩|Sternenaugen',
  '😘|Kuss zuwerfen',
  '😗|Küssendes Gesicht',
  '☺️|Zufriedenes Lächeln',
  '😚|Kuss mit geschlossenen Augen',
  '😙|Kuss mit lachenden Augen',
  '🥲|Lächeln mit Träne',
  '😋|Leckeres Essen genießen',
  '😛|Zunge herausstrecken',
  '😜|Zwinkern mit herausgestreckter Zunge',
  '🤪|Verrücktes Gesicht',
  '😝|Zunge mit zugekniffenen Augen',
  '🤑|Geldgesicht',
  '🤗|Umarmendes Gesicht',
  '🤭|Hand vor dem Mund',
  '🫢|Erstaunt mit Hand vor dem Mund',
  '🫣|Durch die Finger schauen',
  '🤫|Zur Ruhe mahnen',
  '🤔|Nachdenkliches Gesicht',
  '🫡|Salutierendes Gesicht',
  '🤐|Mund mit Reißverschluss',
  '🤨|Hochgezogene Augenbraue',
  '😐|Neutrales Gesicht',
  '😑|Ausdrucksloses Gesicht',
  '😶|Gesicht ohne Mund',
  '🫥|Gestricheltes Gesicht',
  '😶‍🌫️|Gesicht in Wolken',
  '😏|Schmunzelndes Gesicht',
  '😒|Unzufriedenes Gesicht',
  '🙄|Augen verdrehen',
  '😬|Grimasse',
  '😮‍💨|Ausatmendes Gesicht',
  '🤥|Lügendes Gesicht',
  '😌|Erleichtertes Gesicht',
  '😔|Bedrücktes Gesicht',
  '😪|Schläfriges Gesicht',
  '🤤|Sabberndes Gesicht',
  '😴|Schlafendes Gesicht',
  '😷|Gesicht mit Schutzmaske',
  '🤒|Gesicht mit Fieberthermometer',
  '🤕|Gesicht mit Kopfverband',
  '🤢|Übelkeit',
  '🤮|Erbrechendes Gesicht',
  '🤧|Niesendes Gesicht',
  '🥵|Schwitzendes Gesicht vor Hitze',
  '🥶|Frierendes Gesicht',
  '🥴|Benommenes Gesicht',
  '😵|Schwindeliges Gesicht',
  '😵‍💫|Gesicht mit Spiralaugen',
  '🤯|Explodierender Kopf',
  '🤠|Gesicht mit Cowboyhut',
  '🥳|Feierndes Gesicht',
  '🥸|Verkleidetes Gesicht',
  '😎|Lächeln mit Sonnenbrille',
  '🤓|Strebergesicht',
  '🧐|Gesicht mit Monokel',
  '😕|Verwirrtes Gesicht',
  '🫤|Gesicht mit schrägem Mund',
  '😟|Besorgtes Gesicht',
  '🙁|Leicht trauriges Gesicht',
  '☹️|Trauriges Gesicht',
  '😮|Gesicht mit offenem Mund',
  '😯|Sprachloses Gesicht',
  '😲|Erstauntes Gesicht',
  '😳|Errötetes Gesicht',
  '🥺|Flehendes Gesicht',
  '🥹|Gerührtes Gesicht',
  '😦|Besorgtes Gesicht mit offenem Mund',
  '😧|Gequältes Gesicht',
  '😨|Ängstliches Gesicht',
  '😰|Ängstlich mit Schweißtropfen',
  '😥|Traurig und erleichtert',
  '😢|Weinendes Gesicht',
  '😭|Heulendes Gesicht',
  '😱|Vor Angst schreien',
  '😖|Verzweifeltes Gesicht',
  '😣|Leidendes Gesicht',
  '😞|Enttäuschtes Gesicht',
  '😓|Niedergeschlagen mit Schweiß',
  '😩|Erschöpftes Gesicht',
  '😫|Müdes Gesicht',
  '🥱|Gähnendes Gesicht',
  '😤|Schnaubendes Gesicht',
  '😡|Wütendes Gesicht',
  '😠|Verärgertes Gesicht',
  '🤬|Fluchendes Gesicht',
  '😈|Grinsendes Gesicht mit Hörnern',
  '👿|Wütendes Gesicht mit Hörnern',
  '💀|Totenkopf',
  '☠️|Totenkopf mit gekreuzten Knochen',
  '💩|Kothaufen mit Gesicht',
  '🤡|Clownsgesicht',
  '👹|Oger',
  '👺|Kobold',
  '👻|Geist',
  '👽|Außerirdischer',
  '👾|Weltraummonster',
  '🤖|Roboter',
  '😺|Lachende Katze',
  '😸|Grinsende Katze',
  '😹|Katze mit Freudentränen',
  '😻|Katze mit Herzaugen',
  '😼|Schmunzelnde Katze',
  '😽|Küssende Katze',
  '🙀|Erschrockene Katze',
  '😿|Weinende Katze',
  '😾|Schmollende Katze',
  '🙈|Nichts sehen wollen',
  '🙉|Nichts hören wollen',
  '🙊|Nichts sagen wollen',
  '👋|Winkende Hand',
  '🤚|Erhobener Handrücken',
  '🖐️|Hand mit gespreizten Fingern',
  '✋|Erhobene Hand',
  '🖖|Vulkanischer Gruß',
  '🫱|Nach rechts zeigende Hand',
  '🫲|Nach links zeigende Hand',
  '🫳|Handfläche nach unten',
  '🫴|Handfläche nach oben',
  '👌|OK-Zeichen',
  '🤌|Zusammengelegte Fingerspitzen',
  '🤏|Kleine Menge zeigen',
  '✌️|Siegeszeichen',
  '🤞|Gekreuzte Finger',
  '🫰|Fingerherz',
  '🤟|Ich-liebe-dich-Geste',
  '🤘|Rockergeste',
  '🤙|Ruf-mich-an-Geste',
  '👈|Nach links zeigen',
  '👉|Nach rechts zeigen',
  '👆|Nach oben zeigen',
  '🖕|Mittelfinger',
  '👇|Nach unten zeigen',
  '☝️|Erhobener Zeigefinger',
  '🫵|Auf dich zeigen',
  '👍|Daumen hoch',
  '👎|Daumen runter',
  '✊|Erhobene Faust',
  '👊|Faust nach vorne',
  '🤛|Faust nach links',
  '🤜|Faust nach rechts',
  '👏|Klatschende Hände',
  '🙌|Jubelnde Hände',
  '🫶|Herzhände',
  '👐|Offene Hände',
  '🤲|Nach oben gehaltene Handflächen',
  '🤝|Händedruck',
  '🙏|Zusammengelegte Hände',
  '✍️|Schreibende Hand',
  '💅|Nägel lackieren',
  '💪|Angespannter Bizeps',
  '🙍|Stirnrunzelnde Person',
  '🙎|Schmollende Person',
  '🙅|Person mit Nein-Geste',
  '🙆|Person mit OK-Geste',
  '💁|Person mit ausgestreckter Hand',
  '🙋|Person meldet sich',
  '🧏|Gehörlose Person',
  '🙇|Sich verbeugende Person',
  '🤦|Hand vor das Gesicht schlagen',
  '🤷|Schulterzuckende Person',
  '💃|Tanzende Frau',
  '🕺|Tanzender Mann',
  '🫂|Sich umarmende Personen',
].map((entry, index) => {
  const [symbol, label] = entry.split('|');
  return { id: `people_${index}`, symbol, label };
});

export const EMOJI_SETS = {
  things: { label: 'Dinge & Natur', emojis: EMOJIS },
  people: { label: 'Smileys & Gesten', emojis: PEOPLE_EMOJIS },
};
export type EmojiSetId = keyof typeof EMOJI_SETS;

/** Erfolgreiche API-Antwort, die der Browser je normalisiertem Suchtext zwischenspeichert. */
export type Classification = {
  modelId?: string;
  /** Katalog, für den diese Bewertungen gelten. */
  setId: EmojiSetId;
  /** Vollständige Zuordnung der Katalog-IDs zu Wahrscheinlichkeiten im Bereich [0, 1]. */
  scores: Record<string, number>;
  /** Serverseitig gemessene Dauer des Anbieteraufrufs einschließlich Antwortauswertung in ms. */
  elapsedMs: number;
  /** Vom Anbieter gemeldete Kosten in US-Dollar; null bedeutet nicht verfügbar. */
  costUsd: number | null;
  /** Vom Anbieter gemeldeter Modellname oder das angefragte Modell als Ersatzwert. */
  model: string;
  /** Getrimmter Suchtext zur Zuordnung und zum Schutz vor veralteten Ergebnissen. */
  query: string;
};
/** Suchvorschläge in derselben Reihenfolge wie die Beispielbuttons der Oberfläche. */
export const EXAMPLES = [
  'Dinge zum Essen',
  'Gesunde Dinge zum Essen',
  'Ungesunde Dinge zum Essen',
  'Eine Band gründen',
];
